### ISSUE TITLE
crash when setting channel mode (eg +m)

### ISSUE THREAD

**Issue by nilsceberg** [TuxHjaltar/anna#1]
```
Traceback (most recent call last):
  File "src/main.py", line 216, in <module>
    main()
  File "src/main.py", line 212, in main
    anna.start()
  File "/usr/lib/python3.5/site-packages/irc/bot.py", line 328, in start
    super(SingleServerIRCBot, self).start()
  File "/usr/lib/python3.5/site-packages/irc/client.py", line 1249, in start
    self.reactor.process_forever()
  File "/usr/lib/python3.5/site-packages/irc/client.py", line 278, in process_forever
    self.process_once(timeout)
  File "/usr/lib/python3.5/site-packages/irc/client.py", line 259, in process_once
    self.process_data(i)
  File "/usr/lib/python3.5/site-packages/irc/client.py", line 216, in process_data
    c.process_data()
  File "/usr/lib/python3.5/site-packages/irc/client.py", line 582, in process_data
    self._process_line(line)
  File "/usr/lib/python3.5/site-packages/irc/client.py", line 614, in _process_line
    handler(arguments, command, source, tags)
  File "/usr/lib/python3.5/site-packages/irc/client.py", line 663, in _handle_other
    self._handle_event(event)
  File "/usr/lib/python3.5/site-packages/irc/client.py", line 673, in _handle_event
    self.reactor._handle_event(self, event)
  File "/usr/lib/python3.5/site-packages/irc/client.py", line 398, in _handle_event
    result = handler.callback(connection, event)
  File "/usr/lib/python3.5/site-packages/irc/client.py", line 1212, in _dispatcher
    method(connection, event)
  File "src/main.py", line 74, in on_mode
    if event.arguments[1] == self.config['nick'] and event.arguments[0] == "+o":
IndexError: list index out of range
```

**Comment by h0wser** [comment]
confirmed bug, can reproduce

**Comment by nilsceberg** [comment]
well done you @h0wser
